version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  server:
    build: ./Server
    container_name: server
    restart: always
    ports:
      - '5000:5000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/competencesdb
    depends_on:
      - mongo

  client:
    build: ./Client
    container_name: client
    restart: always
    ports:
      - '80:80'
    depends_on:
      - server

volumes:
  mongo_data: 